### ISSUE TITLE
Add Timestamp to ESI Bot Status Messages in #esi-status

### ISSUE THREAD

**Issue by ddouglas** [ddouglas/esi-bot-v2#8]

**Comment by GoldenGnu** [comment]
I wrote this in the slack thread too, but, this may be a better place for it:

Could you make the date be in the users local time zone? I found this: https://api.slack.com/reference/surfaces/formatting#date-formatting I don’t know if that is what you would need to do it, but, I hope it is.

**Comment by ddouglas** [comment]
Resolved with PR #11
